language: node_js
script: 'true'
node_js:
- '9'
before_install:
- rvm install 2.3.1
- gem install sass
- npm install -g gulp-cli
install:
- npm run modal
- npm run toggle
- npm run alert
branches:
  only:
  - master
